name: campus_exchange
description: A dual-state fitness and trading terminal app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  candlesticks: ^2.1.0
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  lottie: ^3.3.2
  http: ^1.2.0
  shared_preferences: ^2.2.3
  permission_handler: ^12.0.1
  health: ^13.3.1
  geolocator: ^14.0.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FF5722"
  image: "assets/images/logo.png"
  android: true
  ios: false
  android_12:
    color: "#FF5722"
    image: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
